### ISSUE TITLE
Topic1-Reading link page unavailable

### ISSUE THREAD

**Issue by YDBev** [DS-XL/ds-intermediate-2023#2]
Link: 
- http://www.oswego.edu/~srp/stats/bp_con.htm 
- http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.720.4424&rep=rep1&type=pdf
- https://online.stat.psu.edu/stat414/node/306/

Cannot be found in document [Topic1/Topic1-Reading.md ](https://github.com/DS-XL/ds-intermediate-2023/blob/4e5c8a91d7ad5c77c600177ca556877f1ed232eb/Topic1/Topic1-Reading.md)

**Comment by emma-oc** [comment]
Thanks for raising this issue! These links have been replaced with newer ones with similar content

**Comment by YDBev** [comment]
Issues resolved, new links added.
